---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: argo-cd
name: argo-cd
repo: https://argoproj.github.io/argo-helm
version: 7.8.28
releaseName: argo-cd
namespace: argo-cd
IncludeCRDs: true
valuesInline:
  configs:
    params:
      server.insecure: true
      server.disable.auth: true
    cm:
      kustomize.buildOptions: --enable-helm
