---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: management-

resources:
  - ../../../modules/azure/aks/provider
  - ../../../stacks/aks-cluster

# patches:
#   - path: patch-xeks.yaml
#     target:
#       kind: XEKS
#       name: aws-eks
#   - path: patch-xnetwork.yaml
#     target:
#       kind: XNetwork
#       name: aws-network
